//
//protoc --go_out=. --go_opt=paths=source_relative pkg/frames/data_frames.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: data_frames.proto

package idl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextFrame) Reset() {
	*x = TextFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_frames_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextFrame) ProtoMessage() {}

func (x *TextFrame) ProtoReflect() protoreflect.Message {
	mi := &file_data_frames_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextFrame.ProtoReflect.Descriptor instead.
func (*TextFrame) Descriptor() ([]byte, []int) {
	return file_data_frames_proto_rawDescGZIP(), []int{0}
}

func (x *TextFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TextFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextFrame) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AudioRawFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Audio       []byte `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	SampleRate  uint32 `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	NumChannels uint32 `protobuf:"varint,5,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"`
	SampleWidth uint32 `protobuf:"varint,6,opt,name=sample_width,json=sampleWidth,proto3" json:"sample_width,omitempty"`
}

func (x *AudioRawFrame) Reset() {
	*x = AudioRawFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_frames_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioRawFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRawFrame) ProtoMessage() {}

func (x *AudioRawFrame) ProtoReflect() protoreflect.Message {
	mi := &file_data_frames_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRawFrame.ProtoReflect.Descriptor instead.
func (*AudioRawFrame) Descriptor() ([]byte, []int) {
	return file_data_frames_proto_rawDescGZIP(), []int{1}
}

func (x *AudioRawFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioRawFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioRawFrame) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *AudioRawFrame) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioRawFrame) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *AudioRawFrame) GetSampleWidth() uint32 {
	if x != nil {
		return x.SampleWidth
	}
	return 0
}

type ImageRawFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image  []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Size   string `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"` // "widthxheight"
	Format string `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Mode   string `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ImageRawFrame) Reset() {
	*x = ImageRawFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_frames_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRawFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRawFrame) ProtoMessage() {}

func (x *ImageRawFrame) ProtoReflect() protoreflect.Message {
	mi := &file_data_frames_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRawFrame.ProtoReflect.Descriptor instead.
func (*ImageRawFrame) Descriptor() ([]byte, []int) {
	return file_data_frames_proto_rawDescGZIP(), []int{2}
}

func (x *ImageRawFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageRawFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageRawFrame) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageRawFrame) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ImageRawFrame) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageRawFrame) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Frame:
	//
	//	*Frame_Text
	//	*Frame_Audio
	//	*Frame_Image
	Frame isFrame_Frame `protobuf_oneof:"frame"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_frames_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_data_frames_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_data_frames_proto_rawDescGZIP(), []int{3}
}

func (m *Frame) GetFrame() isFrame_Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (x *Frame) GetText() *TextFrame {
	if x, ok := x.GetFrame().(*Frame_Text); ok {
		return x.Text
	}
	return nil
}

func (x *Frame) GetAudio() *AudioRawFrame {
	if x, ok := x.GetFrame().(*Frame_Audio); ok {
		return x.Audio
	}
	return nil
}

func (x *Frame) GetImage() *ImageRawFrame {
	if x, ok := x.GetFrame().(*Frame_Image); ok {
		return x.Image
	}
	return nil
}

type isFrame_Frame interface {
	isFrame_Frame()
}

type Frame_Text struct {
	Text *TextFrame `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Frame_Audio struct {
	Audio *AudioRawFrame `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type Frame_Image struct {
	Image *ImageRawFrame `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
}

func (*Frame_Text) isFrame_Frame() {}

func (*Frame_Audio) isFrame_Frame() {}

func (*Frame_Image) isFrame_Frame() {}

var File_data_frames_proto protoreflect.FileDescriptor

var file_data_frames_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x0d, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x52, 0x61, 0x77, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x75,
	0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x57, 0x69, 0x64, 0x74, 0x68, 0x22, 0x89, 0x01, 0x0a,
	0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x61, 0x77, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x61, 0x77, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x36, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x61, 0x77, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x12, 0x5a,
	0x10, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x64,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_frames_proto_rawDescOnce sync.Once
	file_data_frames_proto_rawDescData = file_data_frames_proto_rawDesc
)

func file_data_frames_proto_rawDescGZIP() []byte {
	file_data_frames_proto_rawDescOnce.Do(func() {
		file_data_frames_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_frames_proto_rawDescData)
	})
	return file_data_frames_proto_rawDescData
}

var file_data_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_frames_proto_goTypes = []interface{}{
	(*TextFrame)(nil),     // 0: pipeline_frames.TextFrame
	(*AudioRawFrame)(nil), // 1: pipeline_frames.AudioRawFrame
	(*ImageRawFrame)(nil), // 2: pipeline_frames.ImageRawFrame
	(*Frame)(nil),         // 3: pipeline_frames.Frame
}
var file_data_frames_proto_depIdxs = []int32{
	0, // 0: pipeline_frames.Frame.text:type_name -> pipeline_frames.TextFrame
	1, // 1: pipeline_frames.Frame.audio:type_name -> pipeline_frames.AudioRawFrame
	2, // 2: pipeline_frames.Frame.image:type_name -> pipeline_frames.ImageRawFrame
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_frames_proto_init() }
func file_data_frames_proto_init() {
	if File_data_frames_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_frames_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_frames_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioRawFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_frames_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRawFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_frames_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_frames_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Frame_Text)(nil),
		(*Frame_Audio)(nil),
		(*Frame_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_frames_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_frames_proto_goTypes,
		DependencyIndexes: file_data_frames_proto_depIdxs,
		MessageInfos:      file_data_frames_proto_msgTypes,
	}.Build()
	File_data_frames_proto = out.File
	file_data_frames_proto_rawDesc = nil
	file_data_frames_proto_goTypes = nil
	file_data_frames_proto_depIdxs = nil
}
